import Head from 'next/head'
import styled from '@emotion/styled'
import Landing from '../components/Landing'
import WhyHiveCapital from '../components/WhyHiveCapital'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Hive Capital</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="theme-color"
          content="#222222"
          media="(prefers-color-scheme: dark)"
        />
      </Head>

      <Landing />
      <WhyHiveCapital />
    </Container>
  )
}

const Container = styled.div``
